[tool.poetry]
name = "pihole-backup"
version = "0.1.0"
description = "Pi-hole v6 Backup Tool - Backup Pi-hole to AWS S3"
authors = ["mittalmak"]
readme = "README.md"

[tool.poetry.scripts]
pihole-backup = 'pihole_backup.app:main'

[tool.poetry.dependencies]
python = "^3.11"
boto3 = ">=1.34.0"
pyyaml = ">=6.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
